### ISSUE TITLE
Knee Model may be missing state_equation

### ISSUE THREAD

**Issue by kylembry-sra** [JongRok-Lee/Passive_Dynamic_Walking_Robot#1]
Hello!

Thank you for sharing this passive dynamic walking simulation. While testing this code, I see that there is no state_equation function in the "knee model" directory. If you have that code, would you be able to make it available on this repo?

**Comment by JongRok-Lee** [comment]
Thank you for finding the missing code. I have uploaded the code. Please refer to the latest commit.
